// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$10 from "./sections/adding.tsx";
import * as $$$$$$0 from "./sections/BannerSection.tsx";
import * as $$$$$$11 from "./sections/cc.tsx";
import * as $$$$$$1 from "./sections/Counter.tsx";
import * as $$$$$$12 from "./sections/ddd.tsx";
import * as $$$$$$2 from "./sections/Example.tsx";
import * as $$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/HelloSection.tsx";
import * as $$$$$$13 from "./sections/htmx.tsx";
import * as $$$$$$5 from "./sections/ItWorks.tsx";
import * as $$$$$$6 from "./sections/Let'sgo.tsx";
import * as $$$$$$7 from "./sections/NewSection.tsx";
import * as $$$$$$8 from "./sections/PoweredWithHTMX.tsx";
import * as $$$$$$9 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/adding.tsx": $$$$$$10,
    "site/sections/BannerSection.tsx": $$$$$$0,
    "site/sections/cc.tsx": $$$$$$11,
    "site/sections/Counter.tsx": $$$$$$1,
    "site/sections/ddd.tsx": $$$$$$12,
    "site/sections/Example.tsx": $$$$$$2,
    "site/sections/Footer.tsx": $$$$$$3,
    "site/sections/HelloSection.tsx": $$$$$$4,
    "site/sections/htmx.tsx": $$$$$$13,
    "site/sections/ItWorks.tsx": $$$$$$5,
    "site/sections/Let'sgo.tsx": $$$$$$6,
    "site/sections/NewSection.tsx": $$$$$$7,
    "site/sections/PoweredWithHTMX.tsx": $$$$$$8,
    "site/sections/Theme/Theme.tsx": $$$$$$9,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
